name: Unit Test
description: Run unit tests

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26.0'
        cache: true

    - name: Download dependencies
      shell: bash
      run: go mod download

    - name: Run unit tests
      shell: bash
      run: make test
