package cue

import "github.com/spf13/cobra"

// Cmd is the parent command for cue subcommands.
var Cmd = &cobra.Command{
	Use:   "cue",
	Short: "CUE module management commands",
	Long: `Commands for managing CUE module configuration.

Subcommands:
  init       Initialize a CUE module for tomei manifests
  update     Update tomei module dependencies to the latest version
  scaffold   Generate a CUE manifest scaffold for a resource kind
  eval       Evaluate CUE manifests with tomei configuration
  export     Export CUE manifests as JSON with tomei configuration

Writing manifests:
  Manifests are CUE files in "package tomei". Each resource has apiVersion,
  kind, metadata, and spec fields. Run "tomei cue scaffold <kind>" to
  generate an editable template with all required fields filled in.

  Resource types: Runtime, Tool, ToolSet, Installer, InstallerRepository
  (see "tomei cue scaffold --help" for the full list of supported kinds)

  Versions: Use a pinned version ("1.26.0") for reproducibility, or
  "latest" for automatic resolution. "tomei apply --update-tools" re-resolves
  latest versions.

  Available presets (import via "tomei.terassyi.net/presets/<name>"):
    go      #GoRuntime, #GoTool, #GoToolSet
    rust    #RustRuntime, #CargoBinstall, #BinstallInstaller, #BinstallToolSet
    aqua    #AquaTool, #AquaToolSet
    node    #PnpmRuntime
    python  #UvRuntime
    deno    #DenoRuntime
    bun     #BunRuntime
    brew    #Homebrew, #BrewInstaller, #Formula, #FormulaSet

  Example (Go runtime with aqua tools):
    import gopreset "tomei.terassyi.net/presets/go"
    import "tomei.terassyi.net/presets/aqua"

    goRuntime: gopreset.#GoRuntime & {
        platform: {os: _os, arch: _arch}
        spec: version: "1.26.0"
    }
    cliTools: aqua.#AquaToolSet & {
        metadata: name: "cli-tools"
        spec: tools: jq: {package: "jqlang/jq", version: "latest"}
    }

Platform tag injection (tomei-specific behavior):
  tomei auto-injects CUE @tag() and @if() values for the current platform.
  Plain "cue eval" does NOT do this — use "tomei cue eval" instead, or pass
  tags manually (e.g., "cue eval -t os=darwin -t darwin ...").

  @tag() — string value tags, declared in tomei_platform.cue (generated by
  "tomei cue init"). Use these in field expressions:
    _os:       string @tag(os)        // "linux" or "darwin"
    _arch:     string @tag(arch)      // "amd64" or "arm64"
    _headless: bool | *false @tag(headless,type=bool)

  @if() — boolean tags for file-level conditional inclusion. tomei injects
  a bare tag when the condition matches the current platform:
    @if(darwin)    injected when OS is darwin
    @if(linux)     injected when OS is linux
    @if(amd64)     injected when arch is amd64
    @if(arm64)     injected when arch is arm64
    @if(headless)  injected when headless mode is true
  Files guarded by a non-matching @if() are excluded from evaluation.`,
}

func init() {
	Cmd.AddCommand(initCmd)
	Cmd.AddCommand(updateCmd)
	Cmd.AddCommand(scaffoldCmd)
	Cmd.AddCommand(evalCmd)
	Cmd.AddCommand(exportCmd)
}
