version: "2"
run:
  go: "1.26"
linters:
  enable:
    - errorlint
    - goconst
    - modernize
    - misspell
    - revive
    - testifylint
    - unconvert
    - unparam
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-declaration
        - name: var-naming
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: _test\.go
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
