version: 2

builds:
  - main: ./cmd/tomei
    binary: tomei
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - NOTICE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

git:
  ignore_tags:
    - tomei-cue-v0.0.1
    - tomei-cue-v0.1.0
    - tomei-cue-v0.1.1
    - tomei-cue-v0.1.2
    - tomei-cue-v0.1.3
    - tomei-cue-v0.1.4
    - tomei-cue-v0.1.5
    - tomei-cue-v0.1.6
    - tomei-cue-v0.1.7

release:
  github:
    owner: terassyi
    name: tomei
  draft: false
  prerelease: auto
