name: E2E Test
description: Run E2E tests with Docker or natively

inputs:
  os:
    description: 'Target OS (linux or darwin)'
    required: false
    default: 'linux'
  arch:
    description: 'Target architecture (amd64 or arm64)'
    required: false
    default: ''
  mode:
    description: 'Execution mode (container or native)'
    required: false
    default: 'native'

runs:
  using: composite
  steps:
    # Native mode: use pre-built binaries (no setup-go needed)
    - name: Prepare E2E binaries (Native Mode)
      if: inputs.mode == 'native'
      shell: bash
      run: |
        chmod +x dist/tomei dist/e2e.test dist/ginkgo

    - name: E2E Test (Native Mode)
      if: inputs.mode == 'native'
      shell: bash
      run: |
        TOMEI_E2E_NATIVE=true \
        TOMEI_E2E_BINARY="$(pwd)/dist/tomei" \
          ./dist/ginkgo -v ./dist/e2e.test

    # Container mode: setup-go is safe (tests run inside Docker, no PATH conflict)
    - name: Setup Go (Container Mode)
      if: inputs.mode == 'container'
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.6'
        cache: true

    - name: Download dependencies (Container Mode)
      if: inputs.mode == 'container'
      shell: bash
      run: go mod download

    - name: E2E Test (Container Mode)
      if: inputs.mode == 'container'
      shell: bash
      run: |
        if [ -n "${{ inputs.arch }}" ]; then
          GOARCH=${{ inputs.arch }} make test-e2e
        else
          make test-e2e
        fi
