name: E2E Test
description: Run E2E tests with Docker

inputs:
  arch:
    description: 'Target architecture (amd64 or arm64). If empty, uses host architecture.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.6'
        cache: true

    - name: Download dependencies
      shell: bash
      run: go mod download

    - name: Build and run E2E tests
      shell: bash
      run: |
        if [ -n "${{ inputs.arch }}" ]; then
          GOARCH=${{ inputs.arch }} make test-e2e
        else
          make test-e2e
        fi
