name: E2E Test
description: Run E2E tests with Docker or natively

inputs:
  arch:
    description: 'Target architecture (amd64 or arm64)'
    required: false
    default: ''
  mode:
    description: 'Execution mode (container or native)'
    required: false
    default: 'native'

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.6'
        cache: true

    - name: Download dependencies
      shell: bash
      run: go mod download

    - name: Build toto binary (Native Mode)
      if: inputs.mode == 'native'
      shell: bash
      run: go build -o toto ./cmd/toto

    - name: E2E Test (Native Mode)
      if: inputs.mode == 'native'
      shell: bash
      run: |
        TOTO_E2E_NATIVE=true TOTO_E2E_BINARY=./toto go test -tags=e2e -v ./e2e/... -ginkgo.v

    - name: E2E Test (Container Mode)
      if: inputs.mode == 'container'
      shell: bash
      run: |
        if [ -n "${{ inputs.arch }}" ]; then
          GOARCH=${{ inputs.arch }} make test-e2e
        else
          make test-e2e
        fi
