name: Lint
description: Run linting

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26.0'
        cache: true

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
